Attaching to my_api_container, authentication, authorization, content
[36mauthentication exited with code 0
[0m[35mmy_api_container  |[0m INFO:     Started server process [7]
[35mmy_api_container  |[0m INFO:     Waiting for application startup.
[35mmy_api_container  |[0m INFO:     Application startup complete.
[35mmy_api_container  |[0m INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
[35mmy_api_container  |[0m INFO:     172.21.0.3:44176 - "GET /permissions?username=alice&password=wonderland HTTP/1.1" 200 OK
[35mmy_api_container  |[0m INFO:     172.21.0.3:44178 - "GET /permissions?username=bob&password=builder HTTP/1.1" 200 OK
[35mmy_api_container  |[0m INFO:     172.21.0.3:44180 - "GET /permissions?username=clementine&password=mandarine HTTP/1.1" 403 Forbidden
[35mmy_api_container  |[0m INFO:     172.21.0.4:34478 - "GET /v1/sentiment?username=alice&password=wonderland&sentence=life+is+beautiful HTTP/1.1" 200 OK
[35mmy_api_container  |[0m INFO:     172.21.0.4:34480 - "GET /v2/sentiment?username=alice&password=wonderland&sentence=life+is+beautiful HTTP/1.1" 200 OK
[35mmy_api_container  |[0m INFO:     172.21.0.4:34482 - "GET /v1/sentiment?username=bob&password=builder&sentence=life+is+beautiful HTTP/1.1" 200 OK
[35mmy_api_container  |[0m INFO:     172.21.0.4:34484 - "GET /v2/sentiment?username=bob&password=builder&sentence=life+is+beautiful HTTP/1.1" 403 Forbidden
[33mauthorization exited with code 0
[0m[35mmy_api_container  |[0m INFO:     172.21.0.3:44190 - "GET /v1/sentiment?username=alice&password=wonderland&sentence=life+is+beautiful HTTP/1.1" 200 OK
[35mmy_api_container  |[0m INFO:     172.21.0.3:44192 - "GET /v1/sentiment?username=alice&password=wonderland&sentence=that+sucks HTTP/1.1" 200 OK
[35mmy_api_container  |[0m INFO:     172.21.0.3:44194 - "GET /v2/sentiment?username=alice&password=wonderland&sentence=life+is+beautiful HTTP/1.1" 200 OK
[35mmy_api_container  |[0m INFO:     172.21.0.3:44196 - "GET /v2/sentiment?username=alice&password=wonderland&sentence=that+sucks HTTP/1.1" 200 OK
[32mcontent exited with code 0
[0m[35mmy_api_container  |[0m WARNING:  Invalid HTTP request received.
[35mmy_api_container  |[0m Traceback (most recent call last):
[35mmy_api_container  |[0m   File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 170, in handle_events
[35mmy_api_container  |[0m     event = self.conn.next_event()
[35mmy_api_container  |[0m   File "/usr/local/lib/python3.8/dist-packages/h11/_connection.py", line 443, in next_event
[35mmy_api_container  |[0m     exc._reraise_as_remote_protocol_error()
[35mmy_api_container  |[0m   File "/usr/local/lib/python3.8/dist-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
[35mmy_api_container  |[0m     raise self
[35mmy_api_container  |[0m   File "/usr/local/lib/python3.8/dist-packages/h11/_connection.py", line 425, in next_event
[35mmy_api_container  |[0m     event = self._extract_next_receive_event()
[35mmy_api_container  |[0m   File "/usr/local/lib/python3.8/dist-packages/h11/_connection.py", line 367, in _extract_next_receive_event
[35mmy_api_container  |[0m     event = self._reader(self._receive_buffer)
[35mmy_api_container  |[0m   File "/usr/local/lib/python3.8/dist-packages/h11/_readers.py", line 68, in maybe_read_from_IDLE_client
[35mmy_api_container  |[0m     raise LocalProtocolError("illegal request line")
[35mmy_api_container  |[0m h11._util.RemoteProtocolError: illegal request line
[35mmy_api_container  |[0m INFO:     162.142.125.59:48230 - "GET / HTTP/1.1" 404 Not Found
[35mmy_api_container  |[0m INFO:     162.142.125.59:44160 - "GET / HTTP/1.1" 404 Not Found
